ALTER TABLE "Swimmer"
  DROP COLUMN "rank",
  ADD COLUMN "staff" BOOLEAN NOT NULL DEFAULT false,
  ADD COLUMN "poolMonth" TEXT,
  ADD COLUMN "poolYear" INTEGER,
  ADD COLUMN "syncedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;
